use bid43oc
go

ALTER DATABASE bid43oc
SET ALLOW_SNAPSHOT_ISOLATION ON


ALTER DATABASE bid43oc SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
ALTER DATABASE bid43oc SET READ_COMMITTED_SNAPSHOT ON;
ALTER DATABASE bid43oc SET MULTI_USER;